[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
vault = "8uot8k7km7RtdkxFfXGG2nrRd8CxAG4p2SNJ5sSpmQaz"

[programs.devnet]
vault = "8uot8k7km7RtdkxFfXGG2nrRd8CxAG4p2SNJ5sSpmQaz"

[registry]
url = "https://api.apr.dev"

[provider]
# cluster = "Localnet"
# wallet = "/home/franck/.config/solana/id.json"
cluster = "devnet"
wallet = "/home/franck/.config/solana/devnet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
